name: Hello World
on:
  push:
  workflow_dispatch:
  # repository_dispatch:
  pull_request:

jobs:
  reuse:
    uses: alex-blazh/github-actions/.github/workflows/test-action.yaml@main

  work_with_env:
    environment:
      name: dev
      url: https://google.com
    runs-on: ubuntu-latest
    needs: [ reuse ]
    steps:
      - name: Dev env magic
        run: echo Hello World


  # compose_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: composite
  #     uses: alex-blazh/github-actions/action1@main
  #     with:
  #       name: World

# jobs:
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#     # actions/checkout MUST come before auth
#       - uses: 'actions/checkout@v3'

#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v0.6.0'
#         with:
#           token_format: 'access_token'
#           # token_format: 'id_token'
#           workload_identity_provider: 'projects/732332336349/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#           service_account: 'github-service-account@awesome-tts-326114.iam.gserviceaccount.com'
#       # - name: Setup tmate session
#       #   if: ${{ failure() }}
#       #   uses: mxschmitt/action-tmate@v3

#       # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v0'

#       # Now you can run gcloud commands authenticated as the impersonated service account.
#       - id: 'gcloud'
#         name: 'gcloud'
#         run: |-
#           gcloud compute instances list

#       - id: 'secrets'
#         name: 'secrets'
#         env:
#           TEST_SECRET: ${{ secrets.TEST_SECRET }}
#           SECRETS_CONTEXT: ${{ toJson(secrets) }}
#           EVENT: ${{ toJson(github) }}
#         run: |-
#           echo $EVENT
#           echo $TEST_SECRET
#           echo XXX >> 1.txt
#           echo $TEST_SECRET | base64 -i >> 1.txt
#           cat 1.txt
